POST http://localhost:8000/hex/palette
Content-Type: application/json

{
  "color": {
    "colorDef": {
      "hexMode": {
        "code": "#CC6699"
      }
    }
  }
}

###
POST http://localhost:8888/server/color/convert
Content-Type: application/json

[
  {
    "colorMode": "CMYK_MODE",
    "color": {
      "colorDef": {
        "hsvMode": {
          "hue": 230,
          "saturation": 0.5,
          "value": 0.3
        }
      }
    }
  }
]

###
POST http://localhost:8888/server/rgb/random
Content-Type: application/json

{}

###
POST http://localhost:8889/convertColor
Content-Type: application/json

{
  "colorMode": "HEX_MODE",
  "color": {
    "colorDef": {
      "cmykMode": {
        "cyan": 0.5,
        "magenta": 0.5,
        "yellow": 0.3,
        "key": 0.1
      }
    }
  }
}


###
POST http://localhost:8889/getRandomHexColor

###
POST http://localhost:6061/hex/convert
Content-Type: application/json

{
  "colorMode": "HEX_MODE",
  "color": {
    "colorDef": {
      "cmykMode": {
        "cyan": 0.5,
        "magenta": 0.5,
        "yellow": 0.3,
        "key": 0.1
      }
    }
  }
}

###
POST http://localhost:6061/rgb/convert
Content-Type: application/json

{
  "colorMode": "RGB_MODE",
  "color": {
    "colorDef": {
      "rgbMode": {
        "red": 0,
        "green": 0,
        "blue": 0
      }
    }
  }
}

